# Generated by Django 5.1.2 on 2024-11-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incoming',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='incoming',
            name='dated',
        ),
        migrations.AddField(
            model_name='incoming',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='incoming',
            name='ref',
            field=models.CharField(default='GjWabMaftX', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='incoming',
            name='originally_from',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incoming',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incoming',
            name='received_from',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='from'),
        ),
        migrations.AlterField(
            model_name='incoming',
            name='subject',
            field=models.TextField(blank=True, null=True),
        ),
    ]
