# Generated by Django 5.1.2 on 2024-11-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incoming',
            name='ref',
            field=models.CharField(default='C4bCNeto1r', max_length=10, unique=True),
        ),
    ]
