# Generated by Django 5.1.2 on 2024-11-01 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomings', '0002_remove_incoming_contact_name_remove_incoming_dated_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AlterField(
            model_name='changestatus',
            name='incoming',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='incomings.incoming'),
        ),
        migrations.AlterField(
            model_name='incoming',
            name='ref',
            field=models.CharField(default='qf9jPCtMMC', max_length=10, unique=True),
        ),
    ]
