# Generated by Django 5.1.2 on 2024-11-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomings', '0003_delete_status_alter_changestatus_incoming_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changestatus',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='incoming',
            name='ref',
            field=models.CharField(default='kztsHzO1KB', max_length=10, unique=True),
        ),
    ]
