# Generated by Django 5.1.2 on 2024-11-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomings', '0004_alter_changestatus_date_alter_incoming_ref'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changestatus',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Change Statuses'},
        ),
        migrations.AlterField(
            model_name='incoming',
            name='ref',
            field=models.CharField(default='y3CelykjUu', max_length=10, unique=True),
        ),
    ]
