# Generated by Django 5.1.2 on 2024-11-01 17:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomings', '0005_alter_changestatus_options_alter_incoming_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changestatus',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='incoming',
            name='received_on',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='incoming',
            name='ref',
            field=models.CharField(default='RNsiKMpech', max_length=10, unique=True),
        ),
    ]
