# Generated by Django 5.1.2 on 2024-11-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomings', '0006_alter_changestatus_date_alter_incoming_received_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incoming',
            name='slug',
            field=models.SlugField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='incoming',
            name='ref',
            field=models.CharField(default='Fa44ybOsja', max_length=10, unique=True),
        ),
    ]
