# Generated by Django 5.1.2 on 2024-11-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomings', '0010_alter_incoming_received_on_alter_incoming_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incoming',
            name='file1',
        ),
        migrations.AddField(
            model_name='changestatus',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='updated_files/'),
        ),
        migrations.AlterField(
            model_name='incoming',
            name='ref',
            field=models.CharField(default='K2DRAZH6kP', max_length=10, unique=True),
        ),
    ]
