# Generated by Django 5.1.2 on 2024-11-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomings', '0011_remove_incoming_file1_changestatus_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incoming',
            name='ref',
            field=models.CharField(default='zWTCmmIBBt', max_length=10, unique=True),
        ),
    ]
